replicaCount: 1

image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: "15"

service:
  type: ClusterIP
  port: 5432

persistence:
  storageClassName: standard
  accessMode: ReadWriteOnce
  storage: 5Gi

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

sealedSecrets:
  POSTGRES_DB: AgCc9Jw8AhgB3yN7xEnHlCagEpabFoMYIDp3XB7AkPif1m8efCdw9Er/BBWGolEJZD4OTilmdQGeOywYIlnUOOd0BlVMX9IKVbeqZAfA1WoliX44fn1UPon00zGecV3XW2xSF5UpRiAsdbDikcTCvWGJefSzRpMMLt/boPzfu5TPEFTQfmrvYYo22aLEClhzDjX8ZEw9jbayl6ta75z10viTPdU2eoyr4+0QkU1GahD/LHGnUy+xAvK05sLznuyZwOSkAo0DDBLNN9q9Os/YsFKPDsYw4jMU1pCHpv74qthyKf2GZEJPzXmun/4UApYT59jCOWALeWvgKTH3okbeONn2jwRBuN95hdwOPMAi+IDq2sY8n/29Vfc0mP/ZDjg7gH278opFfOZGpTowuUiXhH7/zI5WirxriJ58cacfPnB6ZJCpfDNu+Rr/SLQ/iw9KgVvhSjXiY9GQ4mzJjY+X24+DB26oOYHykDqsFc/J/RcsHkaZC+up4ej9GSE3nb4nGRVJqePWhUAKBkf0tqunbHWRfrBAihvOgyaVCaWJOvlxDJr95P7UPDK8OVwAiYMfdcmRD9qDme2+TbYIqIOTC3go3MAnNNFS/cm5Tw/L7wBbRSSQJT64BemUO6t50Q44BUntRGKqfrR4nUIIyrZP+dxfJC4P3mWQ/mKzPa30QbqssrIyzAJKN3wrGSu398BCULuRejaAc3A=
  POSTGRES_PASSWORD: AgApTDJLGCK0KASdK1O4n7sF2HnEV4CnCmiqwoUWyfDHDalwdDq0J0EEfH7d1/NZNbtboLnx2v8bqNgyUGOvsYlV/25/ftMq3r3NFG7ploRuPEltPSTzQsIvFCPohcMYVkLXMmnx3n7ZA8yT8U77fJ9Le1p1MqxisHuzMl3ZsqGTncRxmpUuDIKLqXk8zr2ic98guat0jbnqrNtnrmsmbTmb0XWPOUP82gx+5CohawEfnJFYO6P5zc3gywZSi5BD5HWZZYwrm7fVdD5HIaePhTk4lMmfR1EbtIIZGuZ78QSSpRZydK5NKDwUZ+lU9yJ+wUfFaeE9b4VivHIJEzWzlcLCyvgaXreSqnpYPVSyW/MzmighjJgcsZJtvw9ePokBZNHCPd9mhnxW3aWbDmKSZ21wCwZ8k0jf5cAzCM4pmQqaGs9wkSIpZXHtaYyDp2wtkw28MjEqVHjdy1VGnVQRnjARZcOd97aGT77GI0iaKlZfUe2SQ79YrIfcc1acSsgiQig23EAc4SpX2FqxnNUR7/Vc5JGZUD5WzoLsAoQaTegBV0XaZys6fS/S5BGyKIrbcIFOe5n3ZSLjC8I9h4RPno/ssDlHNIxsYotdEIwLQ/RbqBfMhr25STPETnH40bNjC6++0ln7QFq1G2h0ASM9r4JUhEfQnoqlpZ4w1qJeylTRv1BjR17THou2ucIgDOuoiU3qR/aRWD+/ODWWqA==
  POSTGRES_USER: AgCgrR8APKNRSl70bcXzKR4hh0liPd+4kbItS1SHrlCzMnawl5LpIkabUcaiwFYhQyKqh3dzGuBTt+gQpuZKiO5XrxBQ7OTLJ+1uIMz+DL3blHFinxaCRB6wQsJQl559hTASSwnItqDP+uaYmw7BzoRF9LfWGInnSaoZgUeQks7ZKE+x7RDRBavnvG+L0RGfbF4L7Le525skhRbnKTQqviJk0mvEtIpYa6W0MS9cob43FAluu4rHPKrhPnDJ0jIlOT7gTmiXAh1p+zWPjM135KNQJXhAnurNXNoBYCTHuagIGaPVFqnyaBm4PMCz3poDLzhAPuytZL0ob+n2AL2pZNYFJ02nuraRdqa2lJ9hVn6W1KRe9sAQYgrqt/OjZLuynudH66ANRn6uUbDmZFXOW00HbQ/mZXziZEP9V4lYfhBt5OxnlXiPFJ+YBTH0NprP2UAmT1WgAUDIjks0hx4HZlhFMUZDCb0G7SOe9oy4J8Sv8mCtA5t9N5B2diVmLL2TpFSmS4zZ+uodMAXAuSTQyhuIDmy5y0Yh+d2e5RqLC7BBlL9y1kmMqTKx5NEkUTFb1wdRmiMbQPMm0lPtzm05RPe94ejzvZ5zewQpKvZes0BakR7SDhP/yzdrPde5FLI6H1fJQYw+ajjNIHJuPcXnMhtDl7MxKfZ+WBUSmtj+hRBvph/Ljedr5xV10R3JyvipA6b5APDMnUor8w==