apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Chart.Name }}
data:
  default.conf: |
    server {
        listen 80;

        # Serve frontend static files
        root /usr/share/nginx/html;
        index index.html;

        # ✅ Reverse proxy for backend API
        location /tasks {
            proxy_pass http://{{ .Values.backend.serviceName }}:{{ .Values.backend.servicePort }}/tasks;
        }

        # Expose nginx metrics
        location = /nginx_status {
          stub_status;
          access_log off;

          # IMPORTANT: lock it down so it's not public
          allow 127.0.0.1;   # exporter in same pod uses localhost
          deny all;
        }

        # ✅ SPA fallback (optional)
        location / {
            try_files $uri /index.html;
        }
    }
