apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Chart.Name }}
data:
  PORT: "{{ .Values.applicationPort }}"
  DB_PORT: "{{ .Values.db.port }}"
  DB_HOST: "{{ .Values.db.host }}"
  POSTGRES_DB: "{{ .Values.db.name }}"